# Members: **Tabudlong and Misuarez**

### **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [5]:
import numpy as np

#### 2. Print the numpy version

In [16]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [17]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [18]:
arr2 = np.zeros(15)
arr2[6] = 1

print(arr2)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [19]:
arr3 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [20]:
arr4 = np.array([1,2,4,0,4,0])
x = np.where(arr4 != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [21]:
arr5 = np.random.randint(1, 100, size=(4, 4, 4))
print(arr5)

[[[75 90 72 63]
  [41 70  5 90]
  [82 87 52 52]
  [57 53 28 18]]

 [[80 99 69 79]
  [85 31 48 62]
  [18 99  6 21]
  [20 53 66 57]]

 [[ 9 30 13 74]
  [95 33 18 93]
  [97 33 81 10]
  [27 33 76 99]]

 [[82 11 35 59]
  [78 15 25 84]
  [78 26  4 37]
  [70 30 15  8]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [22]:
arr6 = np.random.randint(1,100, size=(15,15))
print(arr6)

[[14  4 48 96 29 84 12  3 55  8 65 78 36  8 64]
 [94 64 76 26 55 26 89  7 30 70 88 94 45 99 39]
 [74 56 81 44 73 57 92  5 57 13 65 96 99  3 67]
 [57 43 36 18 84 12 89 45 12 39 82 92 56 81 42]
 [ 5 28 56 97 23 10 99 77 40 43 39  8 88 81 81]
 [19  5 25 38  5 55 44 30 56 58 17 77 56 46 95]
 [50  1 13 24 10  7 39 79 74 85 89 47 72 64 80]
 [60 75 15 45 97  3 13 36 38 55 19 90 41 44 34]
 [ 6 35 85 46 46 15 32  6 79 96 19 51 62 61 37]
 [43 51 48 66  3 14 20 19 29  9 26 57  6 85 87]
 [84 99 20 13 37 73 59 96 15 53 24 99 74 51 79]
 [32 77 14 37 96 21 75 62 88 61 58 47 72 25 33]
 [17 36  9 48 11 49 45 97 54 35 87  2 60 46 30]
 [25 43 91 53 12 48  8 12 30 25 54 20 71 55 22]
 [90  7 46 32 40 56 55 67 45 91 24 12 44 71 73]]


In [23]:
arr6_min = np.min(arr6)
arr6_max = np.max(arr6)

print(f"Min Value: {arr6_min}")
print(f"Max Value: {arr6_max}")

Min Value: 1
Max Value: 99


#### 9. Create a random array of size 25 and find the mean value

In [14]:
arr7 = np.random.randint(1,100, size=(25))
mean = np.mean(arr7)

print(arr7)
print(mean)

[24 73 86  1 44 68  9 50 38 66 78 94 56  7 64 84 55 56 20 49 53 29 75 68
 85]
53.28


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [15]:
arr8 = np.array([2,4,9])
arr9 = np.array([1,14,6])

print(arr8)
print(arr9)



[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [16]:
print(arr8 + arr9)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [17]:
print(arr8 - arr9)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [18]:
print(arr8 * arr9)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [19]:
print(arr8 / arr9)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [21]:
arr10 = np.array([[10,20,30],[40,50,60],[70,80,90]])

1. Write code to extract the element 50.

In [22]:
print(arr10[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [23]:
arr11 = arr10[1]
print(arr11)

[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [24]:
arr12 = arr10[:,2]
print(arr12)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [25]:
arr13 = arr10[1:3,1:3]
print(arr13)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [26]:
arr14 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [27]:
arr15 = arr14[1:3,1:3]
print(arr15)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [28]:
arr16 = arr14[0, ::2]
print(arr16)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [29]:
reversed_rows = arr14[::-1, :]
print(reversed_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [30]:
last_two_columns = arr14[:, -2:]
print(last_two_columns)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [31]:
arr20 = np.array([11,7,33])
arr21 = np.array([44,5,18])

2. Write code to join arr1 and arr2 into a single 1D array.

In [32]:
joined_array = np.concatenate((arr20, arr21))
print(joined_array)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [33]:
stacked_array = np.vstack((arr20, arr21))
print(stacked_array)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [34]:

arr23 = np.array([[1,2],[3,4]])
arr24 = np.array([[5,6], [7,8]])

5. Write code to join them horizontally (column-wise).

In [35]:
stacked_array2 = np.hstack((arr23, arr24))
print(stacked_array2)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [36]:
stacked_array3 = np.vstack((arr23, arr24))
print(stacked_array3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [ ]:
arr30 = np.arange(10, 30, 2)
arr31 = np.random.randint(1, 50, size=(4, 4))
arr32 = np.random.randint(1,2, size=(2,3,4))

print(f"1D Array:\n {arr30} \n")
print(f"2D Array:\n {arr31} \n")
print(f"3D Array:\n {arr32} \n")

1D Array:
 [10 12 14 16 18 20 22 24 26 28] 

2D Array:
 [[46 32 33 13]
 [ 3 13  9 28]
 [35 19  7 16]
 [ 3  7  5 13]] 

3D Array:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [30]:
newarr = arr30.reshape(2,-1)
last_two_rows = arr31[-2:, :]
arr32[arr32%2 == 0] = -1

print(f"1. \n {newarr} \n")
print(f"2. \n {last_two_rows} \n")
print(f"3. \n {arr32} \n")

1. 
 [[10 12 14 16 18]
 [20 22 24 26 28]] 

2. 
 [[35 19  7 16]
 [ 3  7  5 13]] 

3. 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 



### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [13]:
mean_value = np.mean(arr31)
median_value = np.median(arr31)
std_deviation = np.std(arr31)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation, "\n")

row_sums = np.sum(arr31, axis=1)
print("Row Sums:", row_sums, "\n")

max_value = np.max(arr31)
print("Maximum Value:", max_value)

index = np.where(arr31 == max_value)
print(index)


Mean: 30.0625
Median: 35.0
Standard Deviation: 14.575101843554988 

Row Sums: [137 127 102 115] 

Maximum Value: 48
(array([1, 2]), array([3, 1]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [14]:
large_array = np.random.random((10, 10))
min_per_column = np.min(large_array, axis=0)
top_5_values = np.sort(large_array.flatten())[-5:]

print("10x10 Array:\n", large_array)
print("\n Min per Column:", min_per_column)
print("\n Top 5 Indices:", top_5_values)


10x10 Array:
 [[0.22969671 0.19367196 0.35442009 0.38413945 0.92799032 0.21992083
  0.46683429 0.57688811 0.03603225 0.91090646]
 [0.40880434 0.49437419 0.52668202 0.31801374 0.56521302 0.14401508
  0.55826883 0.81731405 0.64360883 0.38518031]
 [0.05159323 0.09380064 0.18351821 0.90682605 0.64787035 0.17520352
  0.79476483 0.81130386 0.93407798 0.54925124]
 [0.58018336 0.55930964 0.60292422 0.779112   0.10633864 0.59334573
  0.86827343 0.01174989 0.95994006 0.37260972]
 [0.70663926 0.85813202 0.19680585 0.02163113 0.9398347  0.30744922
  0.64585887 0.31133075 0.77868254 0.71149986]
 [0.42936194 0.76382409 0.90770558 0.60667041 0.86406837 0.64841853
  0.35625241 0.62601121 0.57026744 0.18659385]
 [0.39279628 0.4673031  0.66429282 0.46096963 0.31131753 0.43017026
  0.95223286 0.61726603 0.3760157  0.20569129]
 [0.62080551 0.37917878 0.10688115 0.21816892 0.61901832 0.33402827
  0.60869724 0.52077769 0.05099823 0.13435335]
 [0.1144658  0.28646953 0.52483586 0.59274867 0.31333674 0.1565896